### ISSUE TITLE
GreenletExit Exception

### ISSUE THREAD

**Issue by jaddison** [mozilla/django-memcached-pool#7] opened 2012-12-06 05:10 UTC
I'm using gevent, this might be obvious.  I get the occasional exception related to greenlets or gevent.  This is one that I've found in relation to memcache, umemcache and/or django-memcache-pool.  Here's how I've monkeypatched Django in my gunicorn.conf.py:

``` python
bind = '127.0.0.1:1337'
accesslog = "/home/myproject/live/logs/gunicorn-access.log"
errorlog = "/home/myproject/live/logs/gunicorn-error.log"
workers = 5

try:
    from gevent import monkey
    import gevent_psycopg2

    worker_class = 'gevent'

    def do_post_fork(server, worker):
        monkey.patch_all()
        gevent_psycopg2.monkey_patch()

        worker.log.info("Made Psycopg2 Green")

    post_fork = do_post_fork
except ImportError:
    pass
```

My supervisord configuration for gunicorn:

```
[program:gunicorn]
command=/home/myproject/live/bin/gunicorn_django --timeout=120 --max-requests=100 -c /home/myproject/config/production/web/gunicorn.conf.py
directory=/home/myproject/live
user=myproject
autostart=true
autorestart=true
redirect_stderr=True
stdout_logfile=/home/myproject/live/logs/supervisord.log
```

With that configuration, my understand is that if gevent is installed, it will perform the monkeypatching correctly, and it appears to be doing so as I get the log entry shown.

Any thoughts?  Here's the traceback in full:

``` python
Traceback (most recent call last):

  File "/home/myproject/live/lib/python2.6/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)

  File "/home/myproject/live/project/apps/activities/middleware.py", line 37, in process_request
    region = cache.get(key)

  File "/home/myproject/live/lib/python2.6/site-packages/memcachepool/cache.py", line 113, in get
    val = conn.get(key)

  File "/home/myproject/live/lib/python2.6/site-packages/gevent/socket.py", line 432, in recv
    wait_read(sock.fileno(), timeout=self.timeout, event=self._read_event)

  File "/home/myproject/live/lib/python2.6/site-packages/gevent/socket.py", line 169, in wait_read
    switch_result = get_hub().switch()

  File "/home/myproject/live/lib/python2.6/site-packages/gevent/hub.py", line 164, in switch
    return greenlet.switch(self)

GreenletExit
```

I wish I could say it was consistent, but I've seen this only infrequently.

**Comment by jaddison** [comment] 2012-12-07 17:33
Another Traceback I've seen, again quite infrequently:

``` python
Traceback (most recent call last):

File "/home/myproject/live/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
response = callback(request, *callback_args, **callback_kwargs)

File "/home/myproject/live/project/apps/profiles/views/__init__.py", line 138, in login
return render(request, 'profiles/login.html', extra_context)

File "/home/myproject/live/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 44, in render
return HttpResponse(loader.render_to_string(*args, **kwargs),

File "/home/myproject/live/lib/python2.6/site-packages/django/template/loader.py", line 176, in render_to_string
return t.render(context_instance)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 140, in render
return self._render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
return self.nodelist.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 823, in render
bit = self.render_node(node, context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 837, in render_node
return node.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
return compiled_parent._render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
return self.nodelist.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 823, in render
bit = self.render_node(node, context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 837, in render_node
return node.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
return compiled_parent._render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
return self.nodelist.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 823, in render
bit = self.render_node(node, context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 837, in render_node
return node.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
return compiled_parent._render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
return self.nodelist.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 823, in render
bit = self.render_node(node, context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 837, in render_node
return node.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 823, in render
bit = self.render_node(node, context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 837, in render_node
return node.render(context)

File "/home/myproject/live/lib/python2.6/site-packages/django/template/base.py", line 1107, in render
return func(*resolved_args, **resolved_kwargs)

File "/home/myproject/live/lib/python2.6/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 13, in static
return staticfiles_storage.url(path)

File "/home/myproject/live/lib/python2.6/site-packages/django/contrib/staticfiles/storage.py", line 112, in url
hashed_name = self.cache.get(cache_key)

File "/home/myproject/live/lib/python2.6/site-packages/memcachepool/cache.py", line 113, in get
val = conn.get(key)

File "/home/myproject/live/lib/python2.6/site-packages/gevent/socket.py", line 432, in recv
wait_read(sock.fileno(), timeout=self.timeout, event=self._read_event)

File "/home/myproject/live/lib/python2.6/site-packages/gevent/socket.py", line 169, in wait_read
switch_result = get_hub().switch()

File "/home/myproject/live/lib/python2.6/site-packages/gevent/hub.py", line 164, in switch
return greenlet.switch(self)

timeout: timed out
```

**Comment by jaddison** [comment] 2012-12-07 17:35
And one last one that I've received (this one I tweeted you about):

``` python
Traceback (most recent call last):

File "/home/myproject/live/lib/python2.6/site-packages/django/core/handlers/base.py", line 89, in get_response
response = middleware_method(request)

File "/home/myproject/live/project/apps/activities/middleware.py", line 37, in process_request
region = cache.get(key)

File "/home/myproject/live/lib/python2.6/site-packages/memcachepool/cache.py", line 113, in get
val = conn.get(key)

File "/usr/lib/python2.6/contextlib.py", line 34, in __exit__
self.gen.throw(type, value, traceback)

File "/home/myproject/live/lib/python2.6/site-packages/memcachepool/pool.py", line 29, in reserve
yield client

File "/home/myproject/live/lib/python2.6/site-packages/memcachepool/cache.py", line 113, in get
val = conn.get(key)

IOError: No client object
```

**Comment by jaddison** [comment] 2012-12-07 20:50
I had a thought:  I'm running with a single memcached server running on localhost.  Could it have something to do with blacklisting the server due to a timeout?  I'm not sure what would cause a timeout except a bug perhaps in the ultramemcache library.  memcached itself is pretty stable.

I probably should have mentioned versions:
Ubuntu 10.04.4 LTS
memcached 1.4.2
umemcache 1.6
django-memcache-pool 0.3.1
gevent 0.13.8
gevent-psycopg2 0.0.3
greenlet 0.4.0
gunicorn 0.16.1
django 1.4.2

Let me know if I can provide any further data.

**Comment by tarekziade** [comment] 2012-12-07 22:44
I was able to reproduce "IOError: No client object" by restarting the memcache server. The old connector does not get discarded properly and produces the error. 

I am going to add some code to catch this one and replay the call with a fresh connector, and we'll see how it goes from there

**Comment by jaddison** [comment] 2012-12-07 23:12
That sounds good @tarekziade.  I wonder what would cause a timeout, as shown in one of the other trace backs?  Bizarre.

**Comment by tarekziade** [comment] 2012-12-10 13:19
@jaddison can you try the current master ? they are retry-loop at several levels - things should look better

**Comment by jaddison** [comment] 2012-12-10 18:39
I get an exception:

``` python
InvalidTemplateLibrary: ImportError raised loading django.contrib.staticfiles.templatetags.staticfiles: cannot import name MemcachedError
```

**Comment by tarekziade** [comment] 2012-12-10 18:45
ooop @jaddison I forgot to mention: you need to use this branch of umemcache: https://github.com/rbranson/ultramemcache

**Comment by jaddison** [comment] 2012-12-10 18:49
Yes, I figured that out after I commented - I took a look at the network graph on github for umemcache and noticed that fork.  Thanks, I've updated our server.  Unfortunately, all I can do is wait to see if errors continue to appear.

Check back with me in a week maybe?

FYI, we weren't restarting our memcached servers at all when these errors occurred, so I am not sure how/why either umemcache or django-memcached-pool was failing.

**Comment by tarekziade** [comment] 2012-12-10 18:50
sounds good :)  Thanks for the test. :+1:

**Comment by nanonyme** [comment] 2013-02-14 21:45
FWIW the branch mentioned above has since been merged to umemcache but there has not been a release yet.

**Comment by jaddison** [comment] 2013-02-15 00:16
This isn't a concern for me anymore as we're not using this package - if this issue is pointless in your eyes, please close it. Thanks for the follow up!

**Closed as completed** 2013-09-27 20:14 UTC
Labels: bug
